### ISSUE TITLE
升级到新版本会有这个问题

### ISSUE THREAD

**Issue by magicknight** [sunzongzheng/musicApi#3]
`
RangeError: Maximum call stack size exceeded (uncaughtException throw 1 times on pid:xx)
    at toString (<anonymous>)
    at Object.type (/node_modules/flyio/dist/npm/fly.js:90:42)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:144:25)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
    at Object.clone (/node_modules/flyio/dist/npm/fly.js:159:33)
`
之前的1.10版本没有。
用egg.js，nodejs v10.12.0

**Comment by sunzongzheng** [comment]
可以提供复现的步骤吗？

**Comment by sunzongzheng** [comment]
我这边同node版本跑单测正常
![image](https://user-images.githubusercontent.com/12635613/48995690-f9dfbe80-f183-11e8-9991-4718c9e6d0c3.png)

**Comment by yangxuilyx** [comment]
我也遇到了,
node版本：10.13.0，
electron版本：2.0.4，
vue版本：2.5.16，
调用任何接口都返回这个错误

**Comment by sunzongzheng** [comment]
> 我也遇到了,
> node版本：10.13.0，
> electron版本：2.0.4，
> vue版本：2.5.16，
> 调用任何接口都返回这个错误

clone这个仓库，装完依赖跑`npm run test`看看

**Comment by yangxuilyx** [comment]
跳太快。。控制台都显示不完了，最后输出的是：
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.merge (node_modules\flyio\dist\npm\fly.js:170:31)
      at AjaxEngine.engine.onload (node_modules\flyio\dist\npm\fly.js:469:31)
      at AjaxEngine._call (node_modules\flyio\dist\npm\engine-wrapper.js:216:42)
      at E:\Code\js\electron\musicApi\node_modules\flyio\dist\npm\engine-wrapper.js:327:34
      at Request._callback (node_modules\flyio\src\adapter\node.js:36:9)
      at Request.self.callback (node_modules\request\request.js:185:22)
      at Request.<anonymous> (node_modules\request\request.js:1161:10)
      at Gunzip.<anonymous> (node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

我再想想办法把前面的弄出来

**Comment by yangxuilyx** [comment]
测试qq.test.js，中间省略：


  QQ音乐
    1) 搜索歌曲 & keyword=周杰伦
    2) 获取歌曲地址 & 歌曲地址可连通
    3) 获取歌词 & 歌词有内容
    4) 获取歌曲评论 & 评论不为空
    5) 获取歌手详情
    6) 获取歌手列表


  0 passing (4s)
  6 failing

  1) QQ音乐
       搜索歌曲 & keyword=周杰伦:
     Uncaught RangeError: Maximum call stack size exceeded
      at Object.clone (node_modules\flyio\dist\npm\fly.js:143:26)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:155:31)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      ...
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.clone (node_modules\flyio\dist\npm\fly.js:159:33)
      at Object.merge (node_modules\flyio\dist\npm\fly.js:170:31)
      at AjaxEngine.engine.onload (node_modules\flyio\dist\npm\fly.js:469:31)
      at AjaxEngine._call (node_modules\flyio\dist\npm\engine-wrapper.js:216:42)
      at E:\Code\js\electron\musicApi\node_modules\flyio\dist\npm\engine-wrapper.js:327:34
      at Request._callback (node_modules\flyio\src\adapter\node.js:36:9)
      at Request.self.callback (node_modules\request\request.js:185:22)
      at Request.<anonymous> (node_modules\request\request.js:1161:10)
      at Gunzip.<anonymous> (node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sunzongzheng** [comment]
Bug来源于[flyio#157](https://github.com/wendux/fly/issues/157)，经测试在Linux机器直接使用node adaptor会出现这个问题，我这边锁死版本发布了一版，请更新到最新版
`npm upgrade @suen/music-api`

**Comment by yangxuilyx** [comment]
好的，升级测试可以使用了，thanks
